Add tests
dockstore/checker-WDL-templates pull request #28
Opened 2022-04-07 20:03 UTC by aofarrel

Adds very simple automated testing to make sure my workflows do not catastrophically break. This should help me overhaul this workspace without breaking too much as I go along. Tests will be added/subtracted manually as needed. (Eventually I intend on reducing the number of WDLs in this repo, so the manual nature of adding/removing tests is okay with me for the time being.)

Limitations:
* This is not part of circleci as we would need a Dockstore admin to enable circleci in this repo
* miniwdl seems to keep getting certificate errors when calling GitHub (Cromwell does not have this issue) so I made the decision to switch all of the WDLs to use local imports by default -- this makes them slightly less "plug and play" but is arguably better practice anyway (and helped me realize some of the local paths were outdated)
* One workflow gets skipped because it is a mirror of the null model workflow in analysis_pipeline_wdl and would need far too much test data to be mirrored in this repo
* The usefulness of output.txt is debatable as I am not piping miniwdl's output to it, as I think the command line view of miniwdl is easier to parse then what you get in a text file

2022-04-07 20:11 UTC, DailyDreaming requested changes
Hmmm... these tests are a bash script.  Could you do it in python?  The advantage is that python runs all tests and returns all that fail.  Bash scripts will simply break after the first failure.

2022-04-12 22:09 UTC, DailyDreaming requested changes

2022-04-12 22:09 UTC, DailyDreaming commented on tests/tests.py
> +try:
These try/except subprocess calls repeat.  Could you make a function and call it for each to reduce the code.

Ideally this would use a main() function as well.

2026-08-21 01:56 UTC, aofarrel commented
Closed in favor of #32

2026-08-21 01:56 UTC, closed without merging